### ISSUE TITLE
Apostrophes in code blocks - Trainer WDS

### ISSUE THREAD

**Issue by dzaremba90** [Microsoft/MCW-Cognitive-services-and-deep-learning#1]
Hello, 

Please correct the apostrophes displayed in the code blocks in the WDS trainer guide in the Preferred Solution section (June 2018 test fix branch). 
![image](https://user-images.githubusercontent.com/40214167/41995809-cc641486-7a07-11e8-9ed0-e0db20081acc.png)

Thank you, 

Diana

**Comment by kylebunting** [comment]
Fixed.
