### ISSUE TITLE
Issue while creating Machine Learning Experimentation

### ISSUE THREAD

**Issue by GhumanNavneet** [Microsoft/MCW-Cognitive-services-and-deep-learning#10]
In azure portal, Machine Learning Experimentation(preview) updated with Machine Learning Experimentation (Retiring) can you please update that in Hand-on-lab in Exercise 1: Setup Azure Machine Learning accounts.

**Comment by DawnmarieDesJardins** [comment]
Thank you GhumanNavneet!  This workshop is scheduled for an update in November.  I've added the workshop author and marked the issue as an enhancement.

**Comment by cheahengsoon** [comment]
The updated is using **Azure Machine Learning Service Workspace**

**Comment by DawnmarieDesJardins** [comment]
Closing - addressed in December 2018 Update
