### ISSUE TITLE
Suggested Updates: Feedback Welcome

### ISSUE THREAD

**Issue by ZoinerTejada** [Microsoft/MCW-Cognitive-services-and-deep-learning#11]
We are planning an update to be delivered before the calendar year end. We are considering the following changes in this update. Feedback welcome and appreciated. 

*MCW Cog Services & Deep Learning* proposed Changes

Option A - Experience via Azure Databricks. Training within Databricks clusters only.
Option B - Experience via Azure Notebooks. Training locally and within Azure Batch AI.

Proposed changes:
- Remove use of DSVM and the deprecated Azure ML Workbench.
- Replace with a notebook experience (option A or B above) that uses the new AML Python SDK for experiments and model deployment.
- Add content to both whiteboard design session and lab showing provisioning of AML resources using the AML Python SDK from a notebook.
- Add content to both whiteboard design session and lab showing how to leverage AML during experimentation, for model performance logging and for model management.
- Modify lab to deploy model to Azure Container Instance instead of AKS cluster (to save on provisioning time and lab costs).
- Add content to the lab on how to use Azure Search and the related knowledge management capabilities.
- Layer in AML's Auto ML for classification and automated model selection

**Comment by dem108** [comment]
Great initiative! I'd recommend we also showcase how we can leverage Azure Portal + Notebook Widget to monitor the experiments with the new AML Python SDK.

**Comment by ZoinerTejada** [comment]
@dem108 thank you! Regarding your recommendation, I'm unclear which notebook widget you are referring to? Can you elaborate or provide a link to the widget you have in mind? Thanks in advance!

**Comment by DawnmarieDesJardins** [comment]
Comment from Sonia Ang:

Hello, 
 
Are we supposed to suggest what and how to  redo all the AML workbench and the TDSP on Workbench walk throughs to  AML SDK services?  A hefty chunk of  this when i  opened  the HOLs  are still written for Azure Machine Learning Workbench?
Sonia

**Comment by DawnmarieDesJardins** [comment]
Closing - addressed in December 2018 Update
