### ISSUE TITLE
Error:  Notebook 02 Deploy Summarizer Web Service

### ISSUE THREAD

**Issue by GhumanNavneet** [Microsoft/MCW-Cognitive-services-and-deep-learning#18]
We’ve encounter a new issue in this same lab, while running the Notebook 02 “Deploy as Web Service”, cmd 15 is failing with error ‘no such file or directory’.

The gist of the issue is since the lab was last updated, Azure Machine Learning has changed the default path it uses to write out the AML Workspace config file (as used in Cmd 13) . It has changed from `aml_config` to `./.azureml`

**Comment by GhumanNavneet** [comment]
any progress??

**Comment by kfprugger** [comment]
@GhumanNavneet, I verified what you are seeing. I'm hoping the cloud team sees this soon.

**Comment by joelhulen** [comment]
I have updated the notebook and committed to the repo. Please confirm everything works on your end.

**Comment by DawnmarieDesJardins** [comment]
No response, closing as complete.  Will re-open if needed.
