### ISSUE TITLE
Issue with Summarize

### ISSUE THREAD

**Issue by kfprugger** [Microsoft/MCW-Cognitive-services-and-deep-learning#19]
I have a similar issue to the one that already been opened.

I followed all the tasks in the lab (even tore down a workspace, created a new cluster, executed the init script, modified the Advanced Options for the new cluster, but I still keep getting "Cancelled" every time I try to execute Task 01 from 01 Summarize notebook.

Can't progress forward. 02 Deploy Summarizer Web Service is also giving errors.  The same error of "can't find config.json" file that the other issue is pointing to... (https://github.com/Microsoft/MCW-Cognitive-services-and-deep-learning/issues/18)

<img width="713" alt="issue w Dbrix" src="https://user-images.githubusercontent.com/20729981/56147538-7c6feb80-5f76-11e9-885c-1f4e012887ec.png">

**Comment by joelhulen** [comment]
This issue comes down to a timing problem when you install the azureml-sdk library. The instructions were changed explicitly to prevent this issue from happening. Are you getting the "Cancelled" problem before even installing azureml-sdk?

**Comment by kfprugger** [comment]
There was a shared library I was importing from my old WS config. If I _didn't_ have my libary installed and started from scratch, I could continue without the cancellation issue. 

I'll close this out, but why would the presence of the azureml-sdk library cause this, I wonder?

**Comment by joelhulen** [comment]
Basically, the azureml-SDK library has dependencies with conflicting versions. It's been a while since I've researched the issue, but that's the gist of it.
