### ISSUE TITLE
02 Summary Notebook Image Creation Issue

### ISSUE THREAD

**Issue by kfprugger** [Microsoft/MCW-Cognitive-services-and-deep-learning#20]
Issue on Cell 34:

<img width="1511" alt="new error for dbrix" src="https://user-images.githubusercontent.com/20729981/56183273-d9ee5180-5fe3-11e9-82cc-b99f41e82a0c.png">

It seems like there is a problem carving out an **IP address**. Also, why are these ACI images being deployed as an ACI group? Is that the default config? 

Here's the Service Deploy failure from the Azure ML workspace window. I licked into the activity and couldn't find any additional logs. It looks lie the little ACI image created successfully though.

<img width="629" alt="azureml error" src="https://user-images.githubusercontent.com/20729981/56183443-9b0ccb80-5fe4-11e9-8395-23b179c254e9.png">

I verified that I can create a Public IP inside my azure sub with the creds I used for the interactive login as well.

**Comment by joelhulen** [comment]
@kfprugger Are you still having this issue? I've not been able to reproduce it. Did you try re-deploying to see if it automatically created the public IP?

**Comment by kfprugger** [comment]
Yes, it was reproduced in the classroom which was tapping this MCW with @pauldotyu and experienced the same error. 

I've redeployed, but I'm going to try one more time.

**Comment by kfprugger** [comment]
Ok, redeployed both from the AML WS and Dbrix and it's working. 

Thanks for the help, @joelhulen !!!
