### ISSUE TITLE
Dead Link in the Imported Notebook for Cog. Svcs.

### ISSUE THREAD

**Issue by kfprugger** [Microsoft/MCW-Cognitive-services-and-deep-learning#22]
The fender_bender image URL in the cog. svc (notebook 5) no longer works. 

Would suggest an edit to the notebook repo .dbc import.

**Comment by DawnmarieDesJardins** [comment]
@ZoinerTejada @timahenning 
Please review & advise.

**Comment by timahenning** [comment]
Let me check with Zoiner.

**Comment by joelhulen** [comment]
I've updated the image and committed the change to the notebook.
