### ISSUE TITLE
Issue in 05 Cognitive Services.ipynb notebook

### ISSUE THREAD

**Issue by amalgireesh** [microsoft/MCW-Cognitive-services-and-deep-learning#26]
In **Exercise 4**,Task 3, we are using [05 Cognitive Services.ipynb notebook](https://github.com/microsoft/MCW-Cognitive-services-and-deep-learning/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Cognitive%20services%20and%20deep%20learning.md#task-3-completing-the-solution) ,in task 3 of the notebook we need to update the cell with text-analytics base URL, but will get error while we run the cell to invoke the Text Analytics API.![cognitive-error03](https://user-images.githubusercontent.com/48020356/66149861-9939d180-e631-11e9-9b6c-97a3444b8f75.png)To resolve this issue we need to update the [sentiment api url](https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/how-tos/text-analytics-how-to-sentiment-analysis) with /text/analytics/v2.1/sentiment.![cognitive-error01](https://user-images.githubusercontent.com/48020356/66149463-c934a500-e630-11e9-873b-17f3f653d8fc.png)
**for reference;**
![cognitive-error04](https://user-images.githubusercontent.com/48020356/66151968-08192980-e636-11e9-8bee-3de92e22ecea.png)

Thanks,
Amal Gireesh

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with PR #27
