### ISSUE TITLE
Need to update commands

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Cognitive-services-and-deep-learning#28]
Exercise 3:-Task:-1
When we run command 3 and  7 in notebook it shows an error. I ran the below mentioned command to define ta and then it works fine.
Commands are follow:-
import nltk
nltk.download('stopwords')

@DawnmarieDesJardins Please look into this ASAP, we have workshops running.

**Comment by timahenning** [comment]
@Gvashi Thank you letting us know about this issue.  We have a 5-10 business day review and support policy.  https://microsoftcloudworkshop.com/

I will see if we have a resource who can assist you on this issue sooner.  In the meantime, please make sure you have not skipped any steps in the labs.

Thanks,

Tim

**Comment by joelhulen** [comment]
@Gvashi We normally would not do this, but given the fact that you are currently running a workshop, do you have an environment I can connect to and take a look? I'm not sure how long it will take me to get to that point in the lab.

**Comment by joelhulen** [comment]
@Gvashi I've updated the notebook to download the missing library you mentioned (`stopwords`) as well as `punkt`.

**Comment by DawnmarieDesJardins** [comment]
@Gvashi  - I've run the HTML script to update those files for you.  It may take a few minutes to see the change.  If they don't come through, please clear your browser history and open again.
