### ISSUE TITLE
Convert to ONNX ends in error

### ISSUE THREAD

**Issue by pmillart** [microsoft/MCW-Cognitive-services-and-deep-learning#31]
Following previous steps gives the following versions:
Keras version:  2.3.1
Tensorflow version:  2.0.0-beta1

Then the step Convert to ONNX in notebook 04 Deploy Classifier Web Service gives the following error: 
![Annotation 2019-11-15 164624](https://user-images.githubusercontent.com/16237266/68956031-83d6cc00-07c7-11ea-819e-38bc395056aa.jpg)

AttributeError: module 'tensorflow._api.v2.compat.v1' has no attribute 'disable_tensor_equality'

**Comment by DawnmarieDesJardins** [comment]
@pmillart @shirolkar @timahenning 
Thanks Patrick!  This workshop is currently undergoing an update.  We'll make sure to review and incorporate your feedback.

**Comment by shirolkar** [comment]
@pmillart @DawnmarieDesJardins @timahenning 
Thanks for reporting the issue. In the next update, the Exercise 2 / Task 1: Install libraries will ensure that we have the correct versions of all the required libraries. That should address the error reported here.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with December 2019 update merge.
@pmillart - please let us know if you still get the error.
