### ISSUE TITLE
CNTK?

### ISSUE THREAD

**Issue by Rodrigossz** [microsoft/MCW-Cognitive-services-and-deep-learning#35]
There is at least one mention to CNTK. I think that this project was canceled.

The page below returns a 404.

https://docs.microsoft.com/en-us/azure/machine-learning/preview/scenario-image-classification-using-cntk

**Comment by timahenning** [comment]
@Rodrigossz I think the project moved from preview.  https://docs.microsoft.com/en-us/cognitive-toolkit/

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with comment above.  Please reopen the issue if needed.
