### ISSUE TITLE
Typo - dictonary

### ISSUE THREAD

**Issue by Rodrigossz** [microsoft/MCW-Cognitive-services-and-deep-learning#36]
Hello

Lab 03 has a typo: dictonary instead of dictionary.

**Comment by DawnmarieDesJardins** [comment]
Thanks Rodrigo.

**Comment by DawnmarieDesJardins** [comment]
@timahenning
This is in the Notebooks folder - 03 Claim Classification.ipynb doc

![Annotation 2020-02-06 153445](https://user-images.githubusercontent.com/39317565/73988109-8fcdb800-48f6-11ea-9456-d1346f6bf4a7.png)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with PR #38
