### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Cognitive-services-and-deep-learning#41]

**Comment by shirolkar** [comment]
- Migrate the hands-on lab to use Azure Machine Learning Compute Instances instead of Azure Notebooks
- Enhance to train the deep learning model on Azure Machine Learning Compute Cluster
- Enhance to add real-time monitoring of the training run metrics model loss and model accuracy 
- Update the lab to showcase the new capabilities from cognitive services:
   - automatically labeling for various sentiments in text
   - providing sentiment analysis both at the document and sentence level
   - expanded detection and categorization of new entity types

**Comment by DawnmarieDesJardins** [comment]
Feedback received via email from Rodrigo Souza
1)	In your Mobile APP solution, the Cosmos DB icon is not used in the diagram, there is a regular database image. Can you update it for better alignment with the other labs of MCW where the service is used?
2)	For the Cognitive services and deep learning solution, the final notebook could save all the json data extracted from the AI services into a Cosmos DB container, for further reference. Makes sense?

**Comment by kayapperson** [comment]
On the main page under the Hands-On Labs paragraph (https://github.com/microsoft/MCW-Cognitive-services-and-deep-learning#hands-on-lab), replace 'custom AI' with 'Custom Vision AI' in: 'In this hands-on lab, you will implement a solution which combines both pre-built artificial intelligence (AI) in the form of various Cognitive Services, with **custom AI**'.

**Comment by kayapperson** [comment]
> * Migrate the hands-on lab to use Azure Machine Learning Compute Instances instead of **Azure Notebooks**

I see differently on this **Azure Notebooks** point that @shirolkar made. I found using Azure Notebooks to be the simplest PaaS tool to start and not getting bogged down by having starting so many services before jumping into the core lab.

**Comment by kayapperson** [comment]
I ran the 00 Init.ipynp in https://github.com/microsoft/MCW-Cognitive-services-and-deep-learning. The code block #8 threw errors, but the markdown info above this block didn't state that the errors should be ignored like some other code blocks. 
![image](https://user-images.githubusercontent.com/10211411/83914416-cdbcda80-a736-11ea-91e2-5712146549e5.png)

**Comment by sureshpaulraj** [comment]
Please have the sentences in one location and no need to repeat.
![image](https://user-images.githubusercontent.com/8177257/83957375-e4d5f800-a81c-11ea-8d03-48ea9589c25d.png)

**Comment by sureshpaulraj** [comment]
Just a minor feedback Upload Github Reposoitory dialog box (UI) has a new mandatory field added "I trust the content of this repo" to import the content.
![image](https://user-images.githubusercontent.com/8177257/83957729-1e0f6780-a81f-11ea-9f38-40257d56a7f1.png)

**Comment by sureshpaulraj** [comment]
Reference to the solution architecture there is no separate by name "containerized service" available in Azure. Also, the image used belongs to AKS but in the notebooks we use only ACI (Azure Container Instance) for which the image is given below.
![image](https://user-images.githubusercontent.com/8177257/83961004-00a0c480-a844-11ea-94e2-8db666fca9c9.png)

**Comment by shirolkar** [comment]
> Reference to the solution architecture there is no separate Azure service by name "containerized service(s)" available. Also, the image used belongs to AKS but in the notebooks we use only ACI (Azure Container Instance) for deployment the appropriate image is given below. Please replace the image in the solution architecture accordingly.
> ![image](https://user-images.githubusercontent.com/8177257/83961004-00a0c480-a844-11ea-94e2-8db666fca9c9.png)

I have added an explanation to the notebook cell to explain why we are using ACI in the lab whereas in high-scale production deployments Azure Kubernetes Service (AKS) is the recommended option.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #44
