### ISSUE TITLE
Not able to run second cell - error

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Cognitive-services-and-deep-learning#42]
Not able to run second cell, Getting the below error.

![image](https://user-images.githubusercontent.com/45102602/83883054-9fec8b80-a760-11ea-8a8b-3c95ba060ae3.png)

**Comment by timahenning** [comment]
This will handled in the update.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #44
