### ISSUE TITLE
Keras no longer supported

### ISSUE THREAD

**Issue by ErnstRoell** [microsoft/MCW-Cognitive-services-and-deep-learning#50]
Notebook 3 yields an error as keras is no longer standalone supported. The fix is to update tensorflow to version 2.1 and change the first cell in Notebook 3 to the following (i.e. importing keras from tensorflow as submodules)

import string
import re
import os
import numpy as np
import pandas as pd
import urllib.request

import tensorflow as tf
print('Tensorflow version: ', tf.__version__)
from tensorflow import keras 
from tensorflow.keras import models, layers, optimizers, regularizers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Embedding, LSTM
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import pad_sequences

print('Keras version: ', keras.__version__)
print('Tensorflow version: ', tf.__version__)

import azureml.core
from azureml.core import Experiment, Workspace, Run, Datastore
from azureml.core.dataset import Dataset
from azureml.core.compute import ComputeTarget
from azureml.core.model import Model
from azureml.train.dnn import TensorFlow
from azureml.train.estimator import Estimator
from azureml.widgets import RunDetails

print("Azure ML SDK version:", azureml.core.VERSION)

Kind regards, Ernst

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #51
