### ISSUE TITLE
Before the HOL - Documentation Discrepancy with VM creation

### ISSUE THREAD

**Issue by remirz** [Microsoft/MCW-Cognitive-services-and-deep-learning#9]
Task 1, Step 2 instructs to Select Compute and then select Windows Server 2016 Datacenter and then
Step 6 states to Choose a size blade, select D4s_v3. This is not out of sync with instruction further down in the document on step 8 when it refers to NC6 (On the Create blade, review the summary and then select Create). SYnc up the documentation please. Few attendees cannot create DSVM due to limitations with their subscriptions.

**Comment by DawnmarieDesJardins** [comment]
Closing - addressed in December 2018 Update
